import { AminoBytes, Bech32String, Bytes, DisambBytes, JSONBytes, PrefixBytes } from './types';

export type ErrorMessage = string | null;

// Bech32
export function encodeBech32 (hrp: string, data: Bytes): [Bech32String, ErrorMessage];
export function decodeBech32 (bech: Bech32String): [string, Bytes, ErrorMessage];

// Basic encoding
export function encodeByte (byte: number): [AminoBytes, ErrorMessage];
export function encodeByteSlice (bytes: Bytes): [AminoBytes, ErrorMessage];
export function encodeInt8 (int8: number): [AminoBytes, ErrorMessage];
export function encodeInt16 (int16: number): [AminoBytes, ErrorMessage];
export function encodeInt32 (int32: number): [AminoBytes, ErrorMessage];
export function encodeInt64 (int64: number): [AminoBytes, ErrorMessage];
export function encodeVarint (varint: number): [AminoBytes, ErrorMessage];
export function encodeUint8 (uint8: number): [AminoBytes, ErrorMessage];
export function encodeUint16 (uint16: number): [AminoBytes, ErrorMessage];
export function encodeUint32 (uint32: number): [AminoBytes, ErrorMessage];
export function encodeUint64 (uint64: number): [AminoBytes, ErrorMessage];
export function encodeUvarint (uvarint: number): [AminoBytes, ErrorMessage];
export function encodeFloat32 (float: number): [AminoBytes, ErrorMessage];
export function encodeFloat64 (float: number): [AminoBytes, ErrorMessage];
export function encodeBool (bool: boolean): [AminoBytes, ErrorMessage];
export function encodeString (string: string): [AminoBytes, ErrorMessage];
export function encodeTime (time: Date): [AminoBytes, ErrorMessage];

// Basic decoding
export function decodeByte (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeByteSlice (amino: AminoBytes): [Bytes, number, ErrorMessage];
export function decodeInt8 (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeInt16 (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeInt32 (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeInt64 (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeUint8 (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeUint16 (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeUint32 (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeUint64 (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeVarint (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeUvarint (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeFloat32 (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeFloat64 (amino: AminoBytes): [number, number, ErrorMessage];
export function decodeBool (amino: AminoBytes): [boolean, number, ErrorMessage];
export function decodeString (amino: AminoBytes): [string, number, ErrorMessage];
export function decodeTime (amino: AminoBytes): [Date, number, ErrorMessage];

// Meta
export function decodeDisambPrefixBytes (amino: AminoBytes): [DisambBytes, boolean, PrefixBytes, boolean, number, ErrorMessage];
export function nameToDisfix (name: string): [DisambBytes, PrefixBytes];
export function byteSliceSize (bytes: Bytes): number;
export function uvarintSize (uvarint: number): number;
export function varintSize (varint: number): number;

// Typed encoding
export function encodeMultiStoreProofOp (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeIAVLAbsenceOp (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeIAVLValueOp (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePrivKeyLedgerSecp256k1 (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeInfo (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeBIP44Params (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeLocalInfo (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeLedgerInfo (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeOfflineInfo (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMultiInfo (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsg (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeTx (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeAccount (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeVestingAccount (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeBaseAccount (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeBaseVestingAccount (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeContinuousVestingAccount (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeDelayedVestingAccount (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeStdTx (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgSend (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgMultiSend (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgVerifyInvariant (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgWithdrawDelegatorReward (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgWithdrawValidatorCommission (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgSetWithdrawAddress (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeContent (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgSubmitProposal (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgDeposit (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgVote (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeTextProposal (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeSoftwareUpgradeProposal (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgIBCTransfer (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgIBCReceive (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeParameterChangeProposal (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgUnjail (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgCreateValidator (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgEditValidator (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgDelegate (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgUndelegate (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgBeginRedelegate (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeBlockchainMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeBcBlockRequestMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeBcBlockResponseMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeBcNoBlockResponseMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeBcStatusResponseMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeBcStatusRequestMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeConsensusMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeNewRoundStepMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeNewValidBlockMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeProposalMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeProposalPOLMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeBlockPartMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeVoteMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeHasVoteMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeVoteSetMaj23Message (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeVoteSetBitsMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeWALMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMsgInfo (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeTimeoutInfo (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEndHeightMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePubKey (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePrivKey (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePubKeyEd25519 (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePrivKeyEd25519 (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePubKeySecp256k1 (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePrivKeySecp256k1 (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePubKeyMultisigThreshold (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEvidenceMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEvidenceListMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMempoolMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeTxMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePacket (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePacketPing (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePacketPong (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePacketMsg (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePexMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePexRequestMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePexAddrsMessage (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeRemoteSignerMsg (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePubKeyRequest (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePubKeyResponse (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeSignVoteRequest (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeSignedVoteResponse (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeSignProposalRequest (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeSignedProposalResponse (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePingRequest (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodePingResponse (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeTMEventData (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEventDataNewBlock (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEventDataNewBlockHeader (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEventDataTx (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEventDataRoundState (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEventDataNewRound (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEventDataCompleteProposal (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEventDataVote (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEventDataValidatorSetUpdates (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEventDataString (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeEvidence (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeDuplicateVoteEvidence (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMockGoodEvidence (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMockRandomGoodEvidence (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];
export function encodeMockBadEvidence (json: JSONBytes, lengthPrefixed: boolean): [AminoBytes, ErrorMessage];

// Typed decoding
export function decodeMultiStoreProofOp (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeIAVLAbsenceOp (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeIAVLValueOp (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePrivKeyLedgerSecp256k1 (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeInfo (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeBIP44Params (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeLocalInfo (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeLedgerInfo (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeOfflineInfo (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMultiInfo (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsg (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeTx (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeAccount (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeVestingAccount (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeBaseAccount (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeBaseVestingAccount (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeContinuousVestingAccount (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeDelayedVestingAccount (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeStdTx (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgSend (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgMultiSend (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgVerifyInvariant (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgWithdrawDelegatorReward (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgWithdrawValidatorCommission (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgSetWithdrawAddress (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeContent (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgSubmitProposal (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgDeposit (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgVote (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeTextProposal (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeSoftwareUpgradeProposal (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgIBCTransfer (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgIBCReceive (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeParameterChangeProposal (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgUnjail (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgCreateValidator (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgEditValidator (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgDelegate (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgUndelegate (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgBeginRedelegate (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeBlockchainMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeBcBlockRequestMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeBcBlockResponseMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeBcNoBlockResponseMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeBcStatusResponseMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeBcStatusRequestMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeConsensusMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeNewRoundStepMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeNewValidBlockMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeProposalMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeProposalPOLMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeBlockPartMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeVoteMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeHasVoteMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeVoteSetMaj23Message (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeVoteSetBitsMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeWALMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMsgInfo (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeTimeoutInfo (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEndHeightMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePubKey (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePrivKey (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePubKeyEd25519 (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePrivKeyEd25519 (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePubKeySecp256k1 (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePrivKeySecp256k1 (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePubKeyMultisigThreshold (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEvidenceMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEvidenceListMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMempoolMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeTxMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePacket (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePacketPing (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePacketPong (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePacketMsg (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePexMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePexRequestMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePexAddrsMessage (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeRemoteSignerMsg (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePubKeyRequest (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePubKeyResponse (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeSignVoteRequest (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeSignedVoteResponse (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeSignProposalRequest (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeSignedProposalResponse (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePingRequest (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodePingResponse (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeTMEventData (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEventDataNewBlock (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEventDataNewBlockHeader (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEventDataTx (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEventDataRoundState (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEventDataNewRound (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEventDataCompleteProposal (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEventDataVote (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEventDataValidatorSetUpdates (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEventDataString (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeEvidence (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeDuplicateVoteEvidence (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMockGoodEvidence (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMockRandomGoodEvidence (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
export function decodeMockBadEvidence (amino: AminoBytes, lengthPrefixed: boolean): [JSONBytes, ErrorMessage];
