export type Bytes       = Uint8Array;
export type DisambBytes = Bytes;
export type PrefixBytes = Bytes;
export type JSONBytes   = Bytes;
export type AminoBytes  = Bytes;

// Bech32
export function encodeBech32 (hrp: string, data: Bytes): string;
export function decodeBech32 (bech: string): [string, Bytes];

// Basic encoding
export function encodeByte (byte: number): AminoBytes;
export function encodeByteSlice (bytes: Bytes): AminoBytes;
export function encodeInt8 (int8: number): AminoBytes;
export function encodeInt16 (int16: number): AminoBytes;
export function encodeInt32 (int32: number): AminoBytes;
export function encodeInt64 (int64: number): AminoBytes;
export function encodeVarint (varint: number): AminoBytes;
export function encodeUint8 (uint8: number): AminoBytes;
export function encodeUint16 (uint16: number): AminoBytes;
export function encodeUint32 (uint32: number): AminoBytes;
export function encodeUint64 (uint64: number): AminoBytes;
export function encodeUvarint (uvarint: number): AminoBytes;
export function encodeFloat32 (float: number): AminoBytes;
export function encodeFloat64 (float: number): AminoBytes;
export function encodeBool (bool: boolean): AminoBytes;
export function encodeString (string: string): AminoBytes;
export function encodeTime (time: Date): AminoBytes;

// Basic decoding
export function decodeByte (amino: AminoBytes): [number, number];
export function decodeByteSlice (amino: AminoBytes): [Bytes, number];
export function decodeInt8 (amino: AminoBytes): [number, number];
export function decodeInt16 (amino: AminoBytes): [number, number];
export function decodeInt32 (amino: AminoBytes): [number, number];
export function decodeInt64 (amino: AminoBytes): [number, number];
export function decodeUint8 (amino: AminoBytes): [number, number];
export function decodeUint16 (amino: AminoBytes): [number, number];
export function decodeUint32 (amino: AminoBytes): [number, number];
export function decodeUint64 (amino: AminoBytes): [number, number];
export function decodeVarint (amino: AminoBytes): [number, number];
export function decodeUvarint (amino: AminoBytes): [number, number];
export function decodeFloat32 (amino: AminoBytes): [number, number];
export function decodeFloat64 (amino: AminoBytes): [number, number];
export function decodeBool (amino: AminoBytes): [boolean, number];
export function decodeString (amino: AminoBytes): [string, number];
export function decodeTime (amino: AminoBytes): [Date, number];

// Meta
export function decodeDisambPrefixBytes (amino: AminoBytes): [DisambBytes, boolean, PrefixBytes, boolean, number];
export function nameToDisfix (name: string): [DisambBytes, PrefixBytes];
export function byteSliceSize (bytes: Bytes): number;
export function uvarintSize (uvarint: number): number;
export function varintSize (varint: number): number;

// Typed encoding
export function encodeMultiStoreProofOp (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeIAVLAbsenceOp (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeIAVLValueOp (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePrivKeyLedgerSecp256k1 (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeInfo (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeBIP44Params (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeLocalInfo (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeLedgerInfo (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeOfflineInfo (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMultiInfo (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsg (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeTx (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeAccount (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeVestingAccount (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeBaseAccount (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeBaseVestingAccount (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeContinuousVestingAccount (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeDelayedVestingAccount (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeStdTx (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgSend (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgMultiSend (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgVerifyInvariant (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgWithdrawDelegatorReward (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgWithdrawValidatorCommission (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgSetWithdrawAddress (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeContent (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgSubmitProposal (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgDeposit (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgVote (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeTextProposal (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeSoftwareUpgradeProposal (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgIBCTransfer (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgIBCReceive (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeParameterChangeProposal (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgUnjail (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgCreateValidator (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgEditValidator (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgDelegate (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgUndelegate (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgBeginRedelegate (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeBlockchainMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeBcBlockRequestMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeBcBlockResponseMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeBcNoBlockResponseMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeBcStatusResponseMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeBcStatusRequestMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeConsensusMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeNewRoundStepMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeNewValidBlockMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeProposalMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeProposalPOLMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeBlockPartMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeVoteMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeHasVoteMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeVoteSetMaj23Message (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeVoteSetBitsMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeWALMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMsgInfo (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeTimeoutInfo (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEndHeightMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePubKey (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePrivKey (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePubKeyEd25519 (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePrivKeyEd25519 (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePubKeySecp256k1 (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePrivKeySecp256k1 (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePubKeyMultisigThreshold (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEvidenceMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEvidenceListMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMempoolMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeTxMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePacket (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePacketPing (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePacketPong (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePacketMsg (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePexMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePexRequestMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePexAddrsMessage (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeRemoteSignerMsg (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePubKeyRequest (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePubKeyResponse (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeSignVoteRequest (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeSignedVoteResponse (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeSignProposalRequest (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeSignedProposalResponse (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePingRequest (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodePingResponse (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeTMEventData (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEventDataNewBlock (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEventDataNewBlockHeader (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEventDataTx (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEventDataRoundState (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEventDataNewRound (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEventDataCompleteProposal (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEventDataVote (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEventDataValidatorSetUpdates (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEventDataString (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeEvidence (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeDuplicateVoteEvidence (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMockGoodEvidence (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMockRandomGoodEvidence (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;
export function encodeMockBadEvidence (json: JSONBytes, lengthPrefixed: boolean): AminoBytes;

// Typed decoding
export function decodeMultiStoreProofOp (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeIAVLAbsenceOp (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeIAVLValueOp (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePrivKeyLedgerSecp256k1 (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeInfo (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeBIP44Params (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeLocalInfo (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeLedgerInfo (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeOfflineInfo (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMultiInfo (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsg (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeTx (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeAccount (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeVestingAccount (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeBaseAccount (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeBaseVestingAccount (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeContinuousVestingAccount (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeDelayedVestingAccount (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeStdTx (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgSend (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgMultiSend (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgVerifyInvariant (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgWithdrawDelegatorReward (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgWithdrawValidatorCommission (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgSetWithdrawAddress (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeContent (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgSubmitProposal (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgDeposit (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgVote (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeTextProposal (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeSoftwareUpgradeProposal (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgIBCTransfer (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgIBCReceive (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeParameterChangeProposal (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgUnjail (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgCreateValidator (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgEditValidator (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgDelegate (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgUndelegate (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgBeginRedelegate (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeBlockchainMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeBcBlockRequestMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeBcBlockResponseMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeBcNoBlockResponseMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeBcStatusResponseMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeBcStatusRequestMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeConsensusMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeNewRoundStepMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeNewValidBlockMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeProposalMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeProposalPOLMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeBlockPartMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeVoteMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeHasVoteMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeVoteSetMaj23Message (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeVoteSetBitsMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeWALMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMsgInfo (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeTimeoutInfo (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEndHeightMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePubKey (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePrivKey (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePubKeyEd25519 (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePrivKeyEd25519 (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePubKeySecp256k1 (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePrivKeySecp256k1 (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePubKeyMultisigThreshold (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEvidenceMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEvidenceListMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMempoolMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeTxMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePacket (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePacketPing (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePacketPong (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePacketMsg (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePexMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePexRequestMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePexAddrsMessage (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeRemoteSignerMsg (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePubKeyRequest (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePubKeyResponse (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeSignVoteRequest (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeSignedVoteResponse (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeSignProposalRequest (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeSignedProposalResponse (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePingRequest (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodePingResponse (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeTMEventData (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEventDataNewBlock (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEventDataNewBlockHeader (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEventDataTx (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEventDataRoundState (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEventDataNewRound (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEventDataCompleteProposal (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEventDataVote (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEventDataValidatorSetUpdates (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEventDataString (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeEvidence (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeDuplicateVoteEvidence (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMockGoodEvidence (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMockRandomGoodEvidence (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
export function decodeMockBadEvidence (amino: AminoBytes, lengthPrefixed: boolean): JSONBytes;
