// Basic encoding
export function encodeByte (byte: number): Uint8Array;
export function encodeByteSlice (bytes: Uint8Array): Uint8Array;
export function encodeInt8 (int8: number): Uint8Array;
export function encodeInt16 (int16: number): Uint8Array;
export function encodeInt32 (int32: number): Uint8Array;
export function encodeInt64 (int64: number): Uint8Array;
export function encodeVarint (varint: number): Uint8Array;
export function encodeUint8 (uint8: number): Uint8Array;
export function encodeUint16 (uint16: number): Uint8Array;
export function encodeUint32 (uint32: number): Uint8Array;
export function encodeUint64 (uint64: number): Uint8Array;
export function encodeUvarint (uvarint: number): Uint8Array;
export function encodeFloat32 (float: number): Uint8Array;
export function encodeFloat64 (float: number): Uint8Array;
export function encodeBool (bool: boolean): Uint8Array;
export function encodeString (string: string): Uint8Array;
export function encodeTime (time: Date): Uint8Array;

// Basic decoding
export function decodeByte (bytes: Uint8Array): [number, number];
export function decodeByteSlice (bytes: Uint8Array): [Uint8Array, number];
export function decodeInt8 (bytes: Uint8Array): [number, number];
export function decodeInt16 (bytes: Uint8Array): [number, number];
export function decodeInt32 (bytes: Uint8Array): [number, number];
export function decodeInt64 (bytes: Uint8Array): [number, number];
export function decodeUint8 (bytes: Uint8Array): [number, number];
export function decodeUint16 (bytes: Uint8Array): [number, number];
export function decodeUint32 (bytes: Uint8Array): [number, number];
export function decodeUint64 (bytes: Uint8Array): [number, number];
export function decodeVarint (bytes: Uint8Array): [number, number];
export function decodeUvarint (bytes: Uint8Array): [number, number];
export function decodeFloat32 (bytes: Uint8Array): [number, number];
export function decodeFloat64 (bytes: Uint8Array): [number, number];
export function decodeBool (bytes: Uint8Array): [boolean, number];
export function decodeString (bytes: Uint8Array): [string, number];
export function decodeTime (bytes: Uint8Array): [Date, number];

// Meta
export function decodeDisambPrefixBytes (bytes: Uint8Array): [Uint8Array | null, Uint8Array | null, number];
export function nameToDisfix (name: string): [Uint8Array, Uint8Array];
export function byteSliceSize (bytes: Uint8Array): number;
export function uvarintSize (uvarint: number): number;
export function varintSize (varint: number): number;

// Typed encoding
export function encodeMultiStoreProofOp (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeIAVLAbsenceOp (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeIAVLValueOp (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePrivKeyLedgerSecp256k1 (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeBIP44Params (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeLocalInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeLedgerInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeOfflineInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMultiInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsg (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeTx (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeVestingAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeBaseAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeBaseVestingAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeContinuousVestingAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeDelayedVestingAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeStdTx (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgSend (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgMultiSend (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgVerifyInvariant (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgWithdrawDelegatorReward (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgWithdrawValidatorCommission (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgSetWithdrawAddress (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeContent (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgSubmitProposal (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgDeposit (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgVote (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeTextProposal (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeSoftwareUpgradeProposal (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgIBCTransfer (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgIBCReceive (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeParameterChangeProposal (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgUnjail (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgCreateValidator (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgEditValidator (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgDelegate (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgUndelegate (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgBeginRedelegate (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeBlockchainMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeBcBlockRequestMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeBcBlockResponseMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeBcNoBlockResponseMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeBcStatusResponseMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeBcStatusRequestMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeConsensusMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeNewRoundStepMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeNewValidBlockMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeProposalMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeProposalPOLMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeBlockPartMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeVoteMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeHasVoteMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeVoteSetMaj23Message (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeVoteSetBitsMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeWALMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMsgInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeTimeoutInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEndHeightMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePubKey (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePrivKey (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePubKeyEd25519 (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePrivKeyEd25519 (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePubKeySecp256k1 (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePrivKeySecp256k1 (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePubKeyMultisigThreshold (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEvidenceMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEvidenceListMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMempoolMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeTxMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePacket (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePacketPing (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePacketPong (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePacketMsg (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePexMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePexRequestMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePexAddrsMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeRemoteSignerMsg (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePubKeyRequest (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePubKeyResponse (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeSignVoteRequest (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeSignedVoteResponse (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeSignProposalRequest (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeSignedProposalResponse (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePingRequest (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodePingResponse (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeTMEventData (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEventDataNewBlock (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEventDataNewBlockHeader (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEventDataTx (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEventDataRoundState (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEventDataNewRound (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEventDataCompleteProposal (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEventDataVote (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEventDataValidatorSetUpdates (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEventDataString (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeEvidence (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeDuplicateVoteEvidence (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMockGoodEvidence (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMockRandomGoodEvidence (bytes: Uint8Array, bare: boolean): Uint8Array;
export function encodeMockBadEvidence (bytes: Uint8Array, bare: boolean): Uint8Array;

// Typed decoding
export function decodeMultiStoreProofOp (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeIAVLAbsenceOp (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeIAVLValueOp (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePrivKeyLedgerSecp256k1 (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeBIP44Params (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeLocalInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeLedgerInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeOfflineInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMultiInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsg (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeTx (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeVestingAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeBaseAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeBaseVestingAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeContinuousVestingAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeDelayedVestingAccount (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeStdTx (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgSend (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgMultiSend (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgVerifyInvariant (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgWithdrawDelegatorReward (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgWithdrawValidatorCommission (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgSetWithdrawAddress (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeContent (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgSubmitProposal (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgDeposit (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgVote (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeTextProposal (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeSoftwareUpgradeProposal (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgIBCTransfer (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgIBCReceive (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeParameterChangeProposal (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgUnjail (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgCreateValidator (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgEditValidator (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgDelegate (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgUndelegate (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgBeginRedelegate (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeBlockchainMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeBcBlockRequestMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeBcBlockResponseMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeBcNoBlockResponseMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeBcStatusResponseMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeBcStatusRequestMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeConsensusMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeNewRoundStepMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeNewValidBlockMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeProposalMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeProposalPOLMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeBlockPartMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeVoteMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeHasVoteMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeVoteSetMaj23Message (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeVoteSetBitsMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeWALMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMsgInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeTimeoutInfo (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEndHeightMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePubKey (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePrivKey (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePubKeyEd25519 (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePrivKeyEd25519 (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePubKeySecp256k1 (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePrivKeySecp256k1 (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePubKeyMultisigThreshold (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEvidenceMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEvidenceListMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMempoolMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeTxMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePacket (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePacketPing (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePacketPong (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePacketMsg (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePexMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePexRequestMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePexAddrsMessage (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeRemoteSignerMsg (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePubKeyRequest (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePubKeyResponse (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeSignVoteRequest (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeSignedVoteResponse (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeSignProposalRequest (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeSignedProposalResponse (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePingRequest (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodePingResponse (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeTMEventData (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEventDataNewBlock (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEventDataNewBlockHeader (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEventDataTx (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEventDataRoundState (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEventDataNewRound (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEventDataCompleteProposal (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEventDataVote (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEventDataValidatorSetUpdates (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEventDataString (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeEvidence (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeDuplicateVoteEvidence (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMockGoodEvidence (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMockRandomGoodEvidence (bytes: Uint8Array, bare: boolean): Uint8Array;
export function decodeMockBadEvidence (bytes: Uint8Array, bare: boolean): Uint8Array;
