// Bech32
export function encodeBech32 (hrp: string, data: Uint8Array): [string, Error];
export function decodeBech32 (bech: string): [string, Uint8Array, Error];

// Basic encoding
export function encodeByte (byte: number): [Uint8Array, Error];
export function encodeByteSlice (bytes: Uint8Array): [Uint8Array, Error];
export function encodeInt8 (int8: number): [Uint8Array, Error];
export function encodeInt16 (int16: number): [Uint8Array, Error];
export function encodeInt32 (int32: number): [Uint8Array, Error];
export function encodeInt64 (int64: number): [Uint8Array, Error];
export function encodeVarint (varint: number): [Uint8Array, Error];
export function encodeUint8 (uint8: number): [Uint8Array, Error];
export function encodeUint16 (uint16: number): [Uint8Array, Error];
export function encodeUint32 (uint32: number): [Uint8Array, Error];
export function encodeUint64 (uint64: number): [Uint8Array, Error];
export function encodeUvarint (uvarint: number): [Uint8Array, Error];
export function encodeFloat32 (float: number): [Uint8Array, Error];
export function encodeFloat64 (float: number): [Uint8Array, Error];
export function encodeBool (bool: boolean): [Uint8Array, Error];
export function encodeString (string: string): [Uint8Array, Error];
export function encodeTime (time: Date): [Uint8Array, Error];

// Basic decoding
export function decodeByte (amino: Uint8Array): [number, number, Error];
export function decodeByteSlice (amino: Uint8Array): [Uint8Array, number, Error];
export function decodeInt8 (amino: Uint8Array): [number, number, Error];
export function decodeInt16 (amino: Uint8Array): [number, number, Error];
export function decodeInt32 (amino: Uint8Array): [number, number, Error];
export function decodeInt64 (amino: Uint8Array): [number, number, Error];
export function decodeUint8 (amino: Uint8Array): [number, number, Error];
export function decodeUint16 (amino: Uint8Array): [number, number, Error];
export function decodeUint32 (amino: Uint8Array): [number, number, Error];
export function decodeUint64 (amino: Uint8Array): [number, number, Error];
export function decodeVarint (amino: Uint8Array): [number, number, Error];
export function decodeUvarint (amino: Uint8Array): [number, number, Error];
export function decodeFloat32 (amino: Uint8Array): [number, number, Error];
export function decodeFloat64 (amino: Uint8Array): [number, number, Error];
export function decodeBool (amino: Uint8Array): [boolean, number, Error];
export function decodeString (amino: Uint8Array): [string, number, Error];
export function decodeTime (amino: Uint8Array): [Date, number, Error];

// Meta
export function decodeDisambPrefixBytes (amino: Uint8Array): [Uint8Array, boolean, Uint8Array, boolean, number, Error];
export function nameToDisfix (name: string): [Uint8Array, Uint8Array];
export function byteSliceSize (bytes: Uint8Array): number;
export function uvarintSize (uvarint: number): number;
export function varintSize (varint: number): number;

// Typed encoding
export function encodeMultiStoreProofOp (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeIAVLAbsenceOp (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeIAVLValueOp (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePrivKeyLedgerSecp256k1 (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeInfo (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeBIP44Params (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeLocalInfo (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeLedgerInfo (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeOfflineInfo (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMultiInfo (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsg (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeTx (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeAccount (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeVestingAccount (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeBaseAccount (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeBaseVestingAccount (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeContinuousVestingAccount (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeDelayedVestingAccount (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeStdTx (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgSend (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgMultiSend (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgVerifyInvariant (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgWithdrawDelegatorReward (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgWithdrawValidatorCommission (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgSetWithdrawAddress (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeContent (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgSubmitProposal (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgDeposit (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgVote (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeTextProposal (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeSoftwareUpgradeProposal (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgIBCTransfer (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgIBCReceive (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeParameterChangeProposal (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgUnjail (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgCreateValidator (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgEditValidator (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgDelegate (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgUndelegate (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgBeginRedelegate (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeBlockchainMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeBcBlockRequestMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeBcBlockResponseMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeBcNoBlockResponseMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeBcStatusResponseMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeBcStatusRequestMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeConsensusMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeNewRoundStepMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeNewValidBlockMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeProposalMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeProposalPOLMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeBlockPartMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeVoteMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeHasVoteMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeVoteSetMaj23Message (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeVoteSetBitsMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeWALMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMsgInfo (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeTimeoutInfo (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEndHeightMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePubKey (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePrivKey (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePubKeyEd25519 (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePrivKeyEd25519 (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePubKeySecp256k1 (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePrivKeySecp256k1 (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePubKeyMultisigThreshold (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEvidenceMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEvidenceListMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMempoolMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeTxMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePacket (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePacketPing (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePacketPong (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePacketMsg (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePexMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePexRequestMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePexAddrsMessage (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeRemoteSignerMsg (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePubKeyRequest (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePubKeyResponse (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeSignVoteRequest (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeSignedVoteResponse (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeSignProposalRequest (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeSignedProposalResponse (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePingRequest (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodePingResponse (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeTMEventData (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEventDataNewBlock (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEventDataNewBlockHeader (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEventDataTx (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEventDataRoundState (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEventDataNewRound (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEventDataCompleteProposal (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEventDataVote (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEventDataValidatorSetUpdates (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEventDataString (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeEvidence (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeDuplicateVoteEvidence (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMockGoodEvidence (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMockRandomGoodEvidence (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function encodeMockBadEvidence (json: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];

// Typed decoding
export function decodeMultiStoreProofOp (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeIAVLAbsenceOp (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeIAVLValueOp (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePrivKeyLedgerSecp256k1 (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeInfo (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeBIP44Params (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeLocalInfo (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeLedgerInfo (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeOfflineInfo (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMultiInfo (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsg (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeTx (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeAccount (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeVestingAccount (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeBaseAccount (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeBaseVestingAccount (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeContinuousVestingAccount (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeDelayedVestingAccount (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeStdTx (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgSend (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgMultiSend (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgVerifyInvariant (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgWithdrawDelegatorReward (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgWithdrawValidatorCommission (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgSetWithdrawAddress (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeContent (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgSubmitProposal (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgDeposit (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgVote (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeTextProposal (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeSoftwareUpgradeProposal (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgIBCTransfer (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgIBCReceive (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeParameterChangeProposal (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgUnjail (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgCreateValidator (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgEditValidator (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgDelegate (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgUndelegate (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgBeginRedelegate (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeBlockchainMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeBcBlockRequestMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeBcBlockResponseMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeBcNoBlockResponseMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeBcStatusResponseMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeBcStatusRequestMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeConsensusMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeNewRoundStepMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeNewValidBlockMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeProposalMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeProposalPOLMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeBlockPartMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeVoteMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeHasVoteMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeVoteSetMaj23Message (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeVoteSetBitsMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeWALMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMsgInfo (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeTimeoutInfo (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEndHeightMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePubKey (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePrivKey (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePubKeyEd25519 (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePrivKeyEd25519 (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePubKeySecp256k1 (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePrivKeySecp256k1 (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePubKeyMultisigThreshold (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEvidenceMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEvidenceListMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMempoolMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeTxMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePacket (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePacketPing (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePacketPong (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePacketMsg (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePexMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePexRequestMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePexAddrsMessage (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeRemoteSignerMsg (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePubKeyRequest (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePubKeyResponse (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeSignVoteRequest (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeSignedVoteResponse (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeSignProposalRequest (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeSignedProposalResponse (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePingRequest (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodePingResponse (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeTMEventData (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEventDataNewBlock (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEventDataNewBlockHeader (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEventDataTx (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEventDataRoundState (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEventDataNewRound (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEventDataCompleteProposal (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEventDataVote (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEventDataValidatorSetUpdates (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEventDataString (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeEvidence (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeDuplicateVoteEvidence (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMockGoodEvidence (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMockRandomGoodEvidence (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
export function decodeMockBadEvidence (amino: Uint8Array, lengthPrefixed: boolean): [Uint8Array, Error];
