package main

import (
	"github.com/gopherjs/gopherjs/js"
	"github.com/jordansexton/go-amino-js/go/types"
	"github.com/tendermint/go-amino"
)

var cdc = types.Codec

func main() {
	js.Global.Set("Amino", map[string]interface{}{
		"DecodeBool":              amino.DecodeBool,
		"DecodeByte":              amino.DecodeByte,
		"DecodeByteSlice":         amino.DecodeByteSlice,
		"DecodeDisambPrefixBytes": amino.DecodeDisambPrefixBytes,
		"DecodeFloat32":           amino.DecodeFloat32,
		"DecodeFloat64":           amino.DecodeFloat64,
		"DecodeInt16":             amino.DecodeInt16,
		"DecodeInt32":             amino.DecodeInt32,
		"DecodeInt64":             amino.DecodeInt64,
		"DecodeInt8":              amino.DecodeInt8,
		"DecodeString":            amino.DecodeString,
		"DecodeTime":              amino.DecodeTime,
		"DecodeUint16":            amino.DecodeUint16,
		"DecodeUint32":            amino.DecodeUint32,
		"DecodeUint64":            amino.DecodeUint64,
		"DecodeUint8":             amino.DecodeUint8,
		"DecodeUvarint":           amino.DecodeUvarint,
		"DecodeVarint":            amino.DecodeVarint,

		"EncodeBool":      EncodeBool,
		"EncodeByte":      EncodeByte,
		"EncodeByteSlice": EncodeByteSlice,
		"EncodeFloat32":   EncodeFloat32,
		"EncodeFloat64":   EncodeFloat64,
		"EncodeInt16":     EncodeInt16,
		"EncodeInt32":     EncodeInt32,
		"EncodeInt64":     EncodeInt64,
		"EncodeInt8":      EncodeInt8,
		"EncodeString":    EncodeString,
		"EncodeTime":      EncodeTime,
		"EncodeUint16":    EncodeUint16,
		"EncodeUint32":    EncodeUint32,
		"EncodeUint64":    EncodeUint64,
		"EncodeUint8":     EncodeUint8,
		"EncodeUvarint":   EncodeUvarint,
		"EncodeVarint":    EncodeVarint,

		"NameToDisfix":  amino.NameToDisfix,
		"ByteSliceSize": amino.ByteSliceSize,
		"UvarintSize":   amino.UvarintSize,
		"VarintSize":    amino.VarintSize,

		"DecodeIAVLAbsenceOp": DecodeIAVLAbsenceOp,
		"DecodeIAVLValueOp":   DecodeIAVLValueOp,

		"DecodePrivKeyLedgerSecp256k1":         DecodePrivKeyLedgerSecp256k1,
		"DecodeInfo":                           DecodeInfo,
		"DecodeBIP44Params":                    DecodeBIP44Params,
		"DecodeLocalInfo":                      DecodeLocalInfo,
		"DecodeLedgerInfo":                     DecodeLedgerInfo,
		"DecodeOfflineInfo":                    DecodeOfflineInfo,
		"DecodeMultiInfo":                      DecodeMultiInfo,
		"DecodeMsg":                            DecodeMsg,
		"DecodeTx":                             DecodeTx,
		"DecodeAccount":                        DecodeAccount,
		"DecodeVestingAccount":                 DecodeVestingAccount,
		"DecodeBaseAccount":                    DecodeBaseAccount,
		"DecodeBaseVestingAccount":             DecodeBaseVestingAccount,
		"DecodeContinuousVestingAccount":       DecodeContinuousVestingAccount,
		"DecodeDelayedVestingAccount":          DecodeDelayedVestingAccount,
		"DecodeStdTx":                          DecodeStdTx,
		"DecodeMsgSend":                        DecodeMsgSend,
		"DecodeMsgMultiSend":                   DecodeMsgMultiSend,
		"DecodeMsgVerifyInvariant":             DecodeMsgVerifyInvariant,
		"DecodeMsgWithdrawDelegatorReward":     DecodeMsgWithdrawDelegatorReward,
		"DecodeMsgWithdrawValidatorCommission": DecodeMsgWithdrawValidatorCommission,
		"DecodeMsgSetWithdrawAddress":          DecodeMsgSetWithdrawAddress,
		"DecodeContent":                        DecodeContent,
		"DecodeMsgSubmitProposal":              DecodeMsgSubmitProposal,
		"DecodeMsgDeposit":                     DecodeMsgDeposit,
		"DecodeMsgVote":                        DecodeMsgVote,
		"DecodeTextProposal":                   DecodeTextProposal,
		"DecodeSoftwareUpgradeProposal":        DecodeSoftwareUpgradeProposal,
		"DecodeMsgIBCTransfer":                 DecodeMsgIBCTransfer,
		"DecodeMsgIBCReceive":                  DecodeMsgIBCReceive,
		"DecodeParameterChangeProposal":        DecodeParameterChangeProposal,
		"DecodeMsgUnjail":                      DecodeMsgUnjail,
		"DecodeMsgCreateValidator":             DecodeMsgCreateValidator,
		"DecodeMsgEditValidator":               DecodeMsgEditValidator,
		"DecodeMsgDelegate":                    DecodeMsgDelegate,
		"DecodeMsgUndelegate":                  DecodeMsgUndelegate,
		"DecodeMsgBeginRedelegate":             DecodeMsgBeginRedelegate,
		"DecodeBlockchainMessage":              DecodeBlockchainMessage,
		"DecodeBcBlockRequestMessage":          DecodeBcBlockRequestMessage,
		"DecodeBcBlockResponseMessage":         DecodeBcBlockResponseMessage,
		"DecodeBcNoBlockResponseMessage":       DecodeBcNoBlockResponseMessage,
		"DecodeBcStatusResponseMessage":        DecodeBcStatusResponseMessage,
		"DecodeBcStatusRequestMessage":         DecodeBcStatusRequestMessage,
		"DecodeConsensusMessage":               DecodeConsensusMessage,
		"DecodeNewRoundStepMessage":            DecodeNewRoundStepMessage,
		"DecodeNewValidBlockMessage":           DecodeNewValidBlockMessage,
		"DecodeProposalMessage":                DecodeProposalMessage,
		"DecodeProposalPOLMessage":             DecodeProposalPOLMessage,
		"DecodeBlockPartMessage":               DecodeBlockPartMessage,
		"DecodeVoteMessage":                    DecodeVoteMessage,
		"DecodeHasVoteMessage":                 DecodeHasVoteMessage,
		"DecodeVoteSetMaj23Message":            DecodeVoteSetMaj23Message,
		"DecodeVoteSetBitsMessage":             DecodeVoteSetBitsMessage,
		"DecodeWALMessage":                     DecodeWALMessage,
		"DecodeMsgInfo":                        DecodeMsgInfo,
		"DecodeTimeoutInfo":                    DecodeTimeoutInfo,
		"DecodeEndHeightMessage":               DecodeEndHeightMessage,
		"DecodePubKey":                         DecodePubKey,
		"DecodePrivKey":                        DecodePrivKey,
		"DecodePubKeyEd25519":                  DecodePubKeyEd25519,
		"DecodePrivKeyEd25519":                 DecodePrivKeyEd25519,
		"DecodePubKeySecp256k1":                DecodePubKeySecp256k1,
		"DecodePrivKeySecp256k1":               DecodePrivKeySecp256k1,
		"DecodePubKeyMultisigThreshold":        DecodePubKeyMultisigThreshold,
		"DecodeEvidenceMessage":                DecodeEvidenceMessage,
		"DecodeEvidenceListMessage":            DecodeEvidenceListMessage,
		"DecodeMempoolMessage":                 DecodeMempoolMessage,
		"DecodeTxMessage":                      DecodeTxMessage,
		"DecodePacket":                         DecodePacket,
		"DecodePacketPing":                     DecodePacketPing,
		"DecodePacketPong":                     DecodePacketPong,
		"DecodePacketMsg":                      DecodePacketMsg,
		"DecodePexMessage":                     DecodePexMessage,
		"DecodePexRequestMessage":              DecodePexRequestMessage,
		"DecodePexAddrsMessage":                DecodePexAddrsMessage,
		"DecodeRemoteSignerMsg":                DecodeRemoteSignerMsg,
		"DecodePubKeyRequest":                  DecodePubKeyRequest,
		"DecodePubKeyResponse":                 DecodePubKeyResponse,
		"DecodeSignVoteRequest":                DecodeSignVoteRequest,
		"DecodeSignedVoteResponse":             DecodeSignedVoteResponse,
		"DecodeSignProposalRequest":            DecodeSignProposalRequest,
		"DecodeSignedProposalResponse":         DecodeSignedProposalResponse,
		"DecodePingRequest":                    DecodePingRequest,
		"DecodePingResponse":                   DecodePingResponse,
		"DecodeTMEventData":                    DecodeTMEventData,
		"DecodeEventDataNewBlock":              DecodeEventDataNewBlock,
		"DecodeEventDataNewBlockHeader":        DecodeEventDataNewBlockHeader,
		"DecodeEventDataTx":                    DecodeEventDataTx,
		"DecodeEventDataRoundState":            DecodeEventDataRoundState,
		"DecodeEventDataNewRound":              DecodeEventDataNewRound,
		"DecodeEventDataCompleteProposal":      DecodeEventDataCompleteProposal,
		"DecodeEventDataVote":                  DecodeEventDataVote,
		"DecodeEventDataValidatorSetUpdates":   DecodeEventDataValidatorSetUpdates,
		"DecodeEventDataString":                DecodeEventDataString,
		"DecodeEvidence":                       DecodeEvidence,
		"DecodeDuplicateVoteEvidence":          DecodeDuplicateVoteEvidence,
		"DecodeMockGoodEvidence":               DecodeMockGoodEvidence,
		"DecodeMockRandomGoodEvidence":         DecodeMockRandomGoodEvidence,
		"DecodeMockBadEvidence":                DecodeMockBadEvidence,
	})
}
