name: ci

on:
  push:
    branches:    # only for pushes on master
    - master
  pull_request:  # for all PRs regardless of its base branch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t amino-js:$(git rev-parse HEAD) .

    - name: Run unit tests
      run: docker run -it amino-js:$(git rev-parse HEAD) yarn test